config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles   # give all the routes such as edit, show, new, etc. 
  get 'register', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true 
    validates :description, presence: true
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article 
    belongs_to :category
end 

app/models/category.rb
class Category < ApplicationRecord 
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum:3 , maximum: 25}
    validates_uniqueness_of :name, :case_sensitive => false
end 

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles, dependent: :destroy # the dependent means that all the articles will be destroy once the user is deleted
    validates :username, presence: true, uniqueness: {case_sensitive: false} ,length: {minimum:3 , maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 100}, format: {with: VALID_EMAIL_REGEX }
    has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # declare the method as helper method as well 
    helper_method :current_user, :logged_in?
    # the method is available for all controllers
    def current_user
        #return current_user if not find the user from the databse 
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end 
    
    def logged_in?
        # change current_user to bool by adding !! 
        !!current_user
    end 

    def require_user 
        if !logged_in?
            flash[:alert] = "You must login to perfrom the action"
            redirect_to login_path 
        end 
    end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    # perform set_article before doing the methods 
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    # the method must be after checking that the user is logged in -> require_user
    before_action :require_same_user, only: [:edit, :update, :destroy] 

    def index 
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end 

    def show 
    end 

    def new 
        #the following line prevents the nil class when render 'new' page for the first time due to errors msg 
        @article = Article.new
    end 
    
    def edit 
    end 

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        # as soon as we save the article, it has an id associate with it 
        if @article.save 
            # flash heper to display the message
            flash[:notice] = "Article has been created successfully"
            # article_path(@article) == @article -> same result 
            redirect_to @article 
        else 
            render 'new' 
        end 
    end 

    def update 
        if @article.update(article_params) 
            flash[:notice] = "Article has been updated"
            redirect_to @article
        else 
            render 'edit'
        end 
    end 

    def destroy 
        @article.destroy 
        redirect_to articles_path 
    end 

    # anyting below this is a private method 
    private 
    
    def set_article 
        @article = Article.find(params[:id])
    end 

    def article_params 
        params.require(:article).permit(:title, :description, category_ids: [])
    end 

    def require_same_user 
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit/delete your own article"
            redirect_to @article 
        end 
    end 
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    before_action :set_article, only: [:show, :edit, :update]
    before_action :require_admin, except: [:index, :show]

    def show 
        @articles = @category.articles.paginate(page: params[:page], per_page: 4)
    end 

    def new 
        @category = Category.new
    end 

    def index 
        @categories = Category.paginate(page: params[:page], per_page: 4) 
    end 

    def create 
        @category = Category.new(category_params)
        if @category.save 
            flash[:notice] = "The new category has been created"
            redirect_to @category
        else 
            render 'new'
        end 
    end 

    def edit 
    end 
    
    def update 
        if @category.update(category_params)
            flash[:notice] = "The category name has been updated"
            redirect_to @category
        else 
            render 'edit' 
        end 
    end 

    private     
    def set_article 
        @category = Category.find(params[:id])
    end 

    def category_params 
        params.require(:category).permit(:name)
    end 

    def require_admin 
        # first check if the user is logged in
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admin can perform the action"
            redirect_to categories_path
        end 
    end 
    
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 

    end 

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Login successfully"
            redirect_to root_path 
        else
            flash.now[:alert] = "Invalid email or password"
            render 'new'
        end
    end 

    def destroy
        session[:user_id] =  nil 
        flash[:notice] = "Logout successfully"
        redirect_to login_path
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index 
        @users = User.paginate(page: params[:page], per_page: 4)
    end 

    def show 
        #grab all the articles associate with the user
        @articles = @user.articles.paginate(page: params[:page], per_page: 4)
    end 

    def new 
        @user = User.new
    end 

    def edit 
    end 

    def update 
        if @user.update(user_params)
            flash[:notice] = "Profile has been updated"
            redirect_to @user
        else 
            render 'edit'
        end 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Register successfully, hello #{@user.username}"
            redirect_to root_path
        else 
            render 'new' 
        end 
    end 

    def destroy
        @user.destroy 
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account has been deleted"
        redirect_to root_path
    end 
    private 

    #find the user based on the id 
    def set_user
        @user = User.find(params[:id])
    end 

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own profile"
            redirect_to @user
        end 
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
    #method that can be used in view 

    def gravatar_for (user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end 
end

app/views/articles/_article.html.erb
<div class = "container">
    <% @articles.each do |article|%>
        <div class = "row justify-content-md-center">
            <div class = "col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <% if article.user%>
                        <%= link_to article.user.username, user_path(article.user)%>
                    <%end%>
                    <% if article.categories.any?%> 
                        <!-- for each categories render the category partial -->   
                        <div class = "mt-2"><%= render article.categories%></div>
                    <%end%>
                </div> 
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100)%></p>
                    <%= link_to "View", article_path(article), class: "btn btn-outline-success"%>
                    <% if logged_in? && (article.user == current_user || current_user.admin? )  %>
                        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info"%>
                        <%= link_to "Delete", article , class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' }%>
                    <%end%>
                </div>
                <div class="card-footer text-muted">
                    <small> Created <%= time_ago_in_words(article.created_at)%> ago, 
                    <%= time_ago_in_words(article.updated_at)%> edited ago</small>
                </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class = "row justify-content-center">
        <div class = "col-10">
            <%= render 'shared/errors', err: @article%>
            <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f| %>
                <div class = "form-group row">
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded"%>
                    </div>
                </div>
                <br>
                <div class = "form-group row">
                    <%= f.label :description,class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" %>
                    </div>
                </div>
                <br>
                <div class = "form-group row">
                    <%= f.label :category,class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.collection_select :category_ids, Category.all, :id, :name, {prompt: "Make selection from below (can be empty)"},
                                                                                             {multiple: true, size: 3, class: "custom-select shadow rounded"} %>
                    </div>
                </div>
                <div class = "form-group">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <%end%> 
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class = "text-center mt-4" >Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class = "text-center mt-4" >Articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class = "text-center mt-4" >Create New Article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h2 class = "text-center mt-4" ><%= @article.title%></h2>
<div class = "container">
    <div class = "row justify-content-md-center">
        <div class = "col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                By <%= @article.user.username%> 
                <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
                <% if @article.categories.any?%> 
                    <!-- for each categories render the category partial -->   
                    <div class = "mt-2"><%= render @article.categories%></div>
                <%end%>
            </div> 
            <div class="card-body">
                <div id = "description"  class="card-text text-left"><%= simple_format(@article.description)%></div>
                <% if logged_in? && @article.user == current_user%>
                    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info"%>
                    <%= link_to "Delete", @article , class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' }%>
                <%end%>
            </div>
            <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(@article.created_at)%> ago, 
                <%= time_ago_in_words(@article.updated_at)%> edited ago</small>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render  'shared/errors', err: @category%>
            <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f| %>
                <div class = "form-group row">
                    <%= f.label :name,"Category name", class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded" , placeholder: "Enter a name"%>
                    </div>
                </div>
                <br>
                <div class = "form-group">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
<%end%> 

app/views/categories/edit.html.erb
<h1 class = "text-center mt-4" >Edit Category Name</h1> 
<div class="container">
    <div class = "row justify-content-center">
        <div class = "col-10">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class = "text-center mt-4" >Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class = "container">
    <% @categories.each do |category|%>
        <div class = "row justify-content-md-center">
            <div class = "col-4 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success"%></h5>
                        <p class="card-text"><%= pluralize(category.articles.count,"articles")%></p>
                    </div>
                    <div class="card-footer text-muted">
                        <small> Created <%= time_ago_in_words(category.created_at)%> ago, 
                        <%= time_ago_in_words(category.updated_at)%> edited ago</small>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center mt-4" >Create New Category</h1> 
<div class="container">
    <div class = "row justify-content-center">
        <div class = "col-10">
            <%= render  'shared/errors', err: @category%>
            <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f| %>
                <div class = "form-group row">
                    <%= f.label :name,"Category name", class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded" , placeholder: "Enter a name"%>
                    </div>
                </div>
                <br>
                <div class = "form-group">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <%end%> 
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class = "text-center mt-4" >Category: <%= @category.name%></h1>

<% if logged_in? && current_user.admin?%>
    <div class = "text-center mt-4"> 
            <%= link_to "Edit  category", edit_category_path(@category), class: "btn btn-outline-info" %>
    </div>
<%end%>

<h3 class = "text-center mt-4" >Published Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_messages.html.erb
<div class = "container">
    <% flash.each do |name, msg|%>
        <div class="alert alert-<%= name =="notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
    <%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Blog", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link"%>
        </li>
        <% if logged_in?%>
          <% if current_user.admin?%>
            <li class="nav-item">
              <%= link_to "New Category", new_category_path, class: "nav-link"%>
            </li>
          <%end%>
          <li class="nav-item">
            <%= link_to "New Article", new_article_path, class: "nav-link"%>
          </li>
          <li class = "nav-item">
            <%= link_to current_user.username, user_path(current_user), class: "nav-link"%>
          </li>
           <li class = "nav-item">
            <%= link_to "Delete Account", user_path(current_user), class: "nav-link text-danger", method: :delete, data: {comfirm: "Are you sure?"}%>
          </li>
          <li class = "nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link" , method: :delete%>
          </li>
        <%else%>
          <li class = "nav-item">
            <%= link_to "Login", login_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Register", register_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class = "d-flex flex-column">
    <%= render 'layouts/navbar'%>
    <div id = "page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if err.errors.any?%>
    <!-- The first time we dont have @article which can cause error fixed by add @article in new action-->
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading"> Following errors prevented the <%= err.class.name.downcase%> from saving </h4>
        <ul>
            <% err.errors.full_messages.each do |msg|%>
                <li><%= msg%></li>
            <%end%>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>

app/views/users/_form.html.erb
<div class="container">
    <div class = "row justify-content-center">
        <div class = "col-10">
            <%= render  'shared/errors', err: @user%>
            <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f| %>
                <div class = "form-group row">
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded" , placeholder: "Enter a username"%>
                    </div>
                </div>
                <br>
                <div class = "form-group row">
                    <%= f.label :email,class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "abc@gmail.com"%>
                    </div>
                </div>
                <br>
                <div class = "form-group row">
                    <%= f.label :password,class: "col-2 col-form-label text-light" %>
                    <div class = "col-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password"%>
                    </div>
                </div>
                <br>
                <div class = "form-group">
                    <%= f.submit(@user.new_record? ? "Register" : "Update account", class: "btn btn-outline-light btn-lg")%>
                </div>
            <%end%> 
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class = "text-center mt-4" >Edit Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class = "text-center mt-4"> Our Bloggers</h1>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

<div class = "container">
    <% @users.each do |user|%>
        <div class = "row justify-content-md-center">
            <div class = "col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <%= link_to user.username, user%> 
                </div> 
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, size: 150), user %>
                    </h5>
                    <p class="card-text"><%= pluralize(user.articles.count, "article")%></p>
                    <%= link_to "View Profile", user, class: "btn btn-outline-success"%>
                    <% if logged_in?%>
                        <% if user == current_user%>
                            <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info"%>
                        <%end%>
                        <% if current_user.admin?%>
                            <%= link_to "Delete Profile", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete the user? "}%>
                        <%end%>
                    <%end%>
                </div>
                <div class="card-footer text-muted">
                    <small> Joined <%= time_ago_in_words(user.created_at)%></small>
                </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class = "text-center mt-4" >Create New Account</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class = "text-center mt-4" ><%= @user.username%>'s profile</h1>

<%= gravatar_for @user , size: 200%>

<% if logged_in? && (@user == current_user || current_user.admin?)%>
    <div class = "text-center mt-4"> 
            <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
<%end%>

<h3 class = "text-center mt-4" >Published Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>